services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-cloud-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - spring-cloud-network
    restart: unless-stopped

  redis:
    container_name: redis
    hostname: redis
    image: redis
    volumes:
      - "../data/redis:/var/lib/redis/data"
    networks:
      - spring-cloud-network
    expose:
      - 6379
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G

  product-service:
    image: product-service
    container_name: product-service
    hostname: product-service
    environment:
      SPRING_PROFILES_ACTIVE: stage
    ports:
      - "9788:9788"
    networks:
      - spring-cloud-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    entrypoint: ["java","-jar","/product-service-1.0.0.jar"]

  product-cache-service:
    image: product-cache-service
    container_name: product-cache-service
    hostname: product-cache-service
    environment:
      SPRING_PROFILES_ACTIVE: stage
    ports:
      - "9791:9791"
    networks:
      - spring-cloud-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    entrypoint: [ "java","-jar","/product-cache-service-1.0.0.jar" ]

  gateway-service:
    image: gateway-service
    container_name: gateway-service
    hostname: gateway-sergice
    environment:
      SPRING_PROFILES_ACTIVE: stage
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    entrypoint: ["java","-jar","/gateway-service-1.0.0.jar"]

  eureka-server:
    image: eureka-server
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 1G
    entrypoint: ["java","-jar","/eureka-server-1.0.0.jar"]

networks:
  spring-cloud-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: