spring:
  application:
    name: api-gateway
  profiles:
    active: localhost
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/1.0/product-service/**
          filters:
            - StripPrefix=1

        - id: product-cache-service
          uri: lb://product-cache-service
          predicates:
            - Path=/api/1.0/product-cache-service/**
          filters:
            - StripPrefix=1

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: localhost
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: stage
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
